# Generated by Django 3.2.5 on 2022-06-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('score', models.CharField(max_length=30)),
                ('credit', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(default='text', max_length=30)),
                ('second_surname', models.CharField(default='text', max_length=30)),
                ('registration_num', models.CharField(default='text', max_length=30)),
                ('email', models.EmailField(default='example@gmail.com', max_length=140)),
                ('movil', models.CharField(default='text', max_length=30)),
                ('provincia', models.CharField(default='text', max_length=100)),
                ('score', models.CharField(default='text', max_length=30)),
                ('credits', models.CharField(default='text', max_length=140)),
                ('year', models.CharField(default='text', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='attendance_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='student_app.attendance'),
        ),
    ]
