# Generated by Django 3.2.5 on 2022-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='task',
            name='credits',
            field=models.CharField(default='text', max_length=140),
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=140),
        ),
        migrations.AddField(
            model_name='task',
            name='id_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='movil',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='provincia',
            field=models.CharField(default='text', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='registration_num',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='second_surname',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='surname',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='year',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
